---
title: "Reflection_Report"
author: "RE6124019_吳明軒"
format: html
lang: zh
mainfont: "Microsoft JhengHei UI"
toc: true
---

## 前言

很容幸聆聽了台積電資深學長 楊宏基學長 的職場經驗分享,獲益匪淺。學長不僅揭開了這家知名半導體大廠的神秘面紗,更傳授了許多在職場上的觀念與做人處事的原則,另我感觸很深。

## 核心價值:誠信正直為本

楊學長強調,台積電非常重視誠信正直的核心價值。每年員工的年終考評(ICIC)都會審視是否遵守這些原則。一旦有員工觸犯收受賄賂等違紀行為,公司將嚴加處分,可見對員工操守的高度要求。因此,做人做事誠信為本、堅持正直,是台積電企業文化的核心理念。

除了誠信正直外,台積電的核心價值還包括承諾、創新以及客戶信任關係。這四大核心價值貫徹公司的營運理念,成為員工的行為準則。

## 三力一原則:保持學習、溝通協調、平衡生活

### 1. 統計力:持續學習的力量

作為數據科學所的學生,我也覺得必須持續學習新知識，不僅是統計方面的知識，更要不斷看論文跟上時代。唯有透過自我精進,才能掌握最新的分析方法,提供更精確的數據分析建議。

### 2. 簡報力:溝通協調的力量  

在職場上,我們常常需與不同背景的同事合作,因此良好的溝通協調能力至關重要。楊學長建議我們應主動瞭解對方的需求,做好預先溝通,避免不必要的誤會,提升工作效率。此外,"馭繁為簡"的能力也很重要,要將專業術語以通俗易懂的方式解釋清楚。

### 3. 提問力:職場邏輯思維的基本能力

每天的職場生活中,常需要開會、接收不同專業領域的資訊並做出判斷。因此,我們需要培養提出恰當問題的能力,透過邏輯思維去評估他人意見的合理性,而非盲從。這是往上級職位爬升的必備素養。我認為"不懂就問"非常的重要，透過問題的提出，可以雙方資訊對齊，可能沒辦法馬上釐清問題，不過可以讓該怎麼進行下一步的討論更為準確。

### 4. 誠信原則:做一個能被信任的人

在職場上,誠信原則相當重要的，擁有一個能被信任特質,在職場上應該做什麼都相對會比較容易一些。

## 結語

綜合楊學長生動體驗的分享,我們可以深刻體會到台積電作為全球頂尖的科技公司,不僅在專業技術上領先全球,企業文化與員工操守的要求亦是業界典範。而要在這樣的環境中取得成就,誠信正直的人生態度、持續學習的精神、良好的溝通協調能力、平衡工作與生活的智慧,都是不可或缺的關鍵素養。相信透過這次難能可貴的演講,必將成為我們日後在職場上不錯的參考。
